version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env  
    ports:
      - "8080:80"
  invoice_app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    expose:
      - "5000"
    env_file:
      - ./.env
    depends_on:
      - db
